### ISSUE TITLE
Invalid or unexpected token with typescript (ts-node &|| babel)

### ISSUE THREAD

**Issue by hennessyevan** [sundowndev/underbase#286] opened 2019-12-16 20:19 UTC
Trying to use typescript with babel or ts-node results in an error I can't decipher

#### Config
```js
// ::root/underbase.config.js
const path = require('path')

module.exports = {
  db: 'mongodb://localhost:27017/test',
  migrationsDir: path.join(__dirname, 'migrations'),
  collectionName: '_migrations',
  logs: true,
}
```

#### Babel Config
```js
// ::root/babel.config.js
module.exports = {
  presets: ['@babel/typescript', ['@babel/env', { targets: { node: 'current' } }]],
  plugins: [
    ['inline-dotenv', { path: '.env' }],
    '@babel/proposal-optional-chaining',
    '@babel/proposal-nullish-coalescing-operator'
  ],
}
```

#### Directory structure
```
::root
│
└───migrations
│   │
│   └───1.0
│       │   index.ts
│   underbase.config.js
|   babel.config.js
|   tsconfig.json
|   package.json 
```

#### Environment
 - OS: macOS Catalina 10.15.2
 - Node: 12.11.1 _latest via nvm_
 - underbase: 2.1.2

#### Error
```bash
/Users/hennessyevan/.nvm/versions/node/v12.11.1/bin/node:1
����


SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1114:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:429:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:53:3)
    at internal/main/run_main_module.js:7:1
```

#### Notes
My application is a production app that I can't share here however I can go ahead and create a repro if you'd like. I may be configuring something wrong.

**Comment by sundowndev** [comment] 2019-12-16 20:34
Hi, thanks for opening an issue!

What command did you run to make this happen ?

**Comment by hennessyevan** [comment] 2019-12-16 20:51
Any command. It works fine without the `--require` flag so I suspect it may be coming from there. Same error code from `ts-node/register` and `@babel/register`. I tried running from the project i.e. `yarn unibase migrate 1.0` and from globally installed underbase

**Comment by sundowndev** [comment] 2019-12-16 21:11
I'm able to reproduce this. I'll investigate and come back to you very soon.

**Comment by hennessyevan** [comment] 2019-12-16 21:27
Thanks @sundowndev awesome package btw!

**Comment by sundowndev** [comment] 2019-12-17 13:56
It's working fine with babel alone, but it seems to have an issue with the Typescript preset. What you can do, as an alternative, is compile migrations from TS to JS and configure Underbase to run migrations through your dist directory. Like so:

```js
const path = require('path');

module.exports = {
  db: 'mongodb://localhost:27017/underbase_example',
  migrationsDir: path.join(__dirname, '..', 'dist', 'migrations'),
  collectionName: '_migrations',
  logs: true,
};
```

```
$ tree dist
dist
│
├── migrations
│   ├── 1.0
│   │   ├── index.js
│   │   ├── tasks.js
│   │   └── users.js
│   ├── 1.1
│   │   ├── index.js
│   │   └── labels.js
│   ├── 1.2
│   │   ├── index.js
│   │   └── tasks.js
...
```

I'm looking forward to provide a fix for this issue as soon as possible.

**Comment by sundowndev** [comment] 2019-12-17 19:46
I can't reproduce this with ts-node, can you update the package and confirm you're still having the issue ? Thank you

**Comment by hennessyevan** [comment] 2019-12-17 21:01
Yeah same error on version 2.1.3 using both ts-node or babel, local and global

**Closed** 2019-12-18 11:12 UTC
Labels: bug, current sprint

**Comment by sundowndev** [comment] 2019-12-18 11:16
I created a new package to handle .ts files with Babel. It should fixes your issue.

1. Install the new package `yarn add -D @underbase/babel-register-ts`
2. use it like the following `underbase -r @underbase/babel-register-ts --config ...`

Tell me if this fixes your issue :)
